package dalsanto_guicustomcars;

//Matthew Dal Santo
//ITDEV140
//Assignment 10

public class View_GUICustomCars extends javax.swing.JFrame {

    /**
     * Creates new form View_GUICustomCars
     */
    public View_GUICustomCars() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroupCarType = new javax.swing.ButtonGroup();
        lUser = new javax.swing.JLabel();
        lUserName = new javax.swing.JLabel();
        txtFieldFirstName = new javax.swing.JTextField();
        txtFieldLastName = new javax.swing.JTextField();
        lUserAddress = new javax.swing.JLabel();
        txtFieldAddressNumber = new javax.swing.JTextField();
        cBoxAddressStreetDirection = new javax.swing.JComboBox<>();
        txtFieldAddressStreetName = new javax.swing.JTextField();
        cBoxAddressStreetPrefix = new javax.swing.JComboBox<>();
        txtFieldAddressAux = new javax.swing.JTextField();
        txtFieldAddressCity = new javax.swing.JTextField();
        lUserAddressState = new javax.swing.JLabel();
        cBoxAddressState = new javax.swing.JComboBox<>();
        txtFieldAddressZipCode = new javax.swing.JTextField();
        txtFieldPhoneNumber = new javax.swing.JTextField();
        lCar = new javax.swing.JLabel();
        lCarType = new javax.swing.JLabel();
        rButtonCarTypeCompact = new javax.swing.JRadioButton();
        rButtonCarTypeMidSized = new javax.swing.JRadioButton();
        rButtonCarTypeSUV = new javax.swing.JRadioButton();
        lAddPackage = new javax.swing.JLabel();
        cBoxCarPackages = new javax.swing.JComboBox<>();
        bAddCarPackage = new javax.swing.JButton();
        lCarPackages = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCarPackages = new javax.swing.JTextArea();
        bRemoveCarPackage = new javax.swing.JButton();
        lDelivery = new javax.swing.JLabel();
        cBoxDelivery = new javax.swing.JComboBox<>();
        lCarPrice = new javax.swing.JLabel();
        lCarPriceNumber = new javax.swing.JLabel();
        lPackagePrice = new javax.swing.JLabel();
        lPackagePriceNumber = new javax.swing.JLabel();
        lDeliveryPrice = new javax.swing.JLabel();
        lDeliveryPriceNumber = new javax.swing.JLabel();
        bReset = new javax.swing.JButton();
        bRandom = new javax.swing.JButton();
        bSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Custom Cars GUI(Assignment 10)");

        lUser.setText("User");

        lUserName.setText("Name");

        txtFieldFirstName.setText("First Name");

        txtFieldLastName.setText("Last Name");

        lUserAddress.setText("Address");

        txtFieldAddressNumber.setText("Street Number");

        cBoxAddressStreetDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFieldAddressStreetName.setText("Street Name");

        cBoxAddressStreetPrefix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFieldAddressAux.setText("Aux");

        txtFieldAddressCity.setText("City");

        lUserAddressState.setText("State");

        cBoxAddressState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFieldAddressZipCode.setText("Zip Code");

        txtFieldPhoneNumber.setText("Phone Number");

        lCar.setText("Car");

        lCarType.setText("Type");

        bGroupCarType.add(rButtonCarTypeCompact);
        rButtonCarTypeCompact.setText("Compact");

        bGroupCarType.add(rButtonCarTypeMidSized);
        rButtonCarTypeMidSized.setText("Mid Sized");

        bGroupCarType.add(rButtonCarTypeSUV);
        rButtonCarTypeSUV.setText("SUV");

        lAddPackage.setText("Add Package");

        cBoxCarPackages.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bAddCarPackage.setText("Add");

        lCarPackages.setText("Car Packages");

        txtAreaCarPackages.setColumns(20);
        txtAreaCarPackages.setRows(5);
        jScrollPane1.setViewportView(txtAreaCarPackages);

        bRemoveCarPackage.setText("Remove");

        lDelivery.setText("Delivery");

        cBoxDelivery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lCarPrice.setText("Car Price: ");

        lCarPriceNumber.setText("_____");

        lPackagePrice.setText("Price of Packages: ");

        lPackagePriceNumber.setText("_____");

        lDeliveryPrice.setText("Price of Delivery: ");

        lDeliveryPriceNumber.setText("_____");

        bReset.setText("Reset Order");

        bRandom.setText("Random Entry");

        bSubmit.setText("Submit Order");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rButtonCarTypeMidSized)
                            .addComponent(rButtonCarTypeSUV)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rButtonCarTypeCompact)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cBoxCarPackages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bAddCarPackage))
                                            .addComponent(lAddPackage)
                                            .addComponent(lDelivery))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bRemoveCarPackage)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lCarPackages)))
                                    .addComponent(lCarType)
                                    .addComponent(lCar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lUser)
                                            .addComponent(lUserName)
                                            .addComponent(txtFieldAddressAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFieldAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lUserAddress)
                                                    .addComponent(txtFieldAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cBoxAddressStreetDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtFieldAddressStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cBoxAddressStreetPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtFieldAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cBoxAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lUserAddressState)))
                                                .addGap(62, 62, 62)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lCarPrice)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lCarPriceNumber)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lDeliveryPrice)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lDeliveryPriceNumber))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lPackagePrice)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lPackagePriceNumber)))
                                                        .addGap(0, 204, Short.MAX_VALUE))))))))
                            .addComponent(cBoxDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(163, 163, 163))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bReset)
                        .addGap(18, 18, 18)
                        .addComponent(bRandom)
                        .addGap(18, 18, 18)
                        .addComponent(bSubmit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lUserAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFieldAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cBoxAddressStreetDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldAddressStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cBoxAddressStreetPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFieldAddressAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCarPrice)
                            .addComponent(lCarPriceNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPackagePrice)
                            .addComponent(lPackagePriceNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBoxAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lUserAddressState)
                            .addComponent(lDeliveryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDeliveryPriceNumber))
                        .addGap(13, 13, 13)
                        .addComponent(txtFieldAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lCar)
                        .addGap(26, 26, 26)
                        .addComponent(lCarType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rButtonCarTypeCompact)
                        .addGap(18, 18, 18)
                        .addComponent(rButtonCarTypeMidSized)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rButtonCarTypeSUV)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCarPackages)
                            .addComponent(lAddPackage))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cBoxCarPackages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bAddCarPackage)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bRemoveCarPackage)
                                    .addComponent(lDelivery))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bReset)
                            .addComponent(bRandom)
                            .addComponent(bSubmit))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_GUICustomCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_GUICustomCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_GUICustomCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_GUICustomCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_GUICustomCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddCarPackage;
    private javax.swing.ButtonGroup bGroupCarType;
    private javax.swing.JButton bRandom;
    private javax.swing.JButton bRemoveCarPackage;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSubmit;
    private javax.swing.JComboBox<String> cBoxAddressState;
    private javax.swing.JComboBox<String> cBoxAddressStreetDirection;
    private javax.swing.JComboBox<String> cBoxAddressStreetPrefix;
    private javax.swing.JComboBox<String> cBoxCarPackages;
    private javax.swing.JComboBox<String> cBoxDelivery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAddPackage;
    private javax.swing.JLabel lCar;
    private javax.swing.JLabel lCarPackages;
    private javax.swing.JLabel lCarPrice;
    private javax.swing.JLabel lCarPriceNumber;
    private javax.swing.JLabel lCarType;
    private javax.swing.JLabel lDelivery;
    private javax.swing.JLabel lDeliveryPrice;
    private javax.swing.JLabel lDeliveryPriceNumber;
    private javax.swing.JLabel lPackagePrice;
    private javax.swing.JLabel lPackagePriceNumber;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lUserAddress;
    private javax.swing.JLabel lUserAddressState;
    private javax.swing.JLabel lUserName;
    private javax.swing.JRadioButton rButtonCarTypeCompact;
    private javax.swing.JRadioButton rButtonCarTypeMidSized;
    private javax.swing.JRadioButton rButtonCarTypeSUV;
    private javax.swing.JTextArea txtAreaCarPackages;
    private javax.swing.JTextField txtFieldAddressAux;
    private javax.swing.JTextField txtFieldAddressCity;
    private javax.swing.JTextField txtFieldAddressNumber;
    private javax.swing.JTextField txtFieldAddressStreetName;
    private javax.swing.JTextField txtFieldAddressZipCode;
    private javax.swing.JTextField txtFieldFirstName;
    private javax.swing.JTextField txtFieldLastName;
    private javax.swing.JTextField txtFieldPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
