package dalsanto_guicustomcars;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;

//Matthew Dal Santo
//ITDEV140
//Assignment 10

public class View_GUICustomCars extends javax.swing.JFrame {

    /**
     * Creates new form View_GUICustomCars
     */
    public View_GUICustomCars() {
        initComponents();
        
        // Set Delivery Options
        cBoxDelivery.removeAllItems();
        cBoxDelivery.addItem("No");
        cBoxDelivery.addItem("Yes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroupCarType = new javax.swing.ButtonGroup();
        lUser = new javax.swing.JLabel();
        lUserName = new javax.swing.JLabel();
        txtFieldFirstName = new javax.swing.JTextField();
        txtFieldLastName = new javax.swing.JTextField();
        lUserAddress = new javax.swing.JLabel();
        txtFieldAddressNumber = new javax.swing.JTextField();
        cBoxAddressStreetDirection = new javax.swing.JComboBox<>();
        txtFieldAddressStreetName = new javax.swing.JTextField();
        cBoxAddressStreetSuffix = new javax.swing.JComboBox<>();
        txtFieldAddressAux = new javax.swing.JTextField();
        txtFieldAddressCity = new javax.swing.JTextField();
        lUserAddressState = new javax.swing.JLabel();
        cBoxAddressState = new javax.swing.JComboBox<>();
        txtFieldAddressZipCode = new javax.swing.JTextField();
        txtFieldPhoneNumber = new javax.swing.JTextField();
        lCar = new javax.swing.JLabel();
        lCarType = new javax.swing.JLabel();
        rButtonCarTypeCompact = new javax.swing.JRadioButton();
        rButtonCarTypeMidSized = new javax.swing.JRadioButton();
        rButtonCarTypeSUV = new javax.swing.JRadioButton();
        lAddPackage = new javax.swing.JLabel();
        cBoxCarPackage = new javax.swing.JComboBox<>();
        bAddCarPackage = new javax.swing.JButton();
        lCarPackages = new javax.swing.JLabel();
        bRemoveCarPackage = new javax.swing.JButton();
        lDelivery = new javax.swing.JLabel();
        cBoxDelivery = new javax.swing.JComboBox<>();
        lCarPrice = new javax.swing.JLabel();
        lCarPriceNumber = new javax.swing.JLabel();
        lPackagePrice = new javax.swing.JLabel();
        lPackagePriceNumber = new javax.swing.JLabel();
        lDeliveryPrice = new javax.swing.JLabel();
        lDeliveryPriceNumber = new javax.swing.JLabel();
        bSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCarPackages = new javax.swing.JList<>();
        labelCarImage = new javax.swing.JLabel();
        lUserPhoneNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Custom Cars GUI(Assignment 10)");

        lUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lUser.setText("User");

        lUserName.setText("Name");

        txtFieldFirstName.setText("First Name");

        txtFieldLastName.setText("Last Name");

        lUserAddress.setText("Address");

        txtFieldAddressNumber.setText("Street Number");

        cBoxAddressStreetDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFieldAddressStreetName.setText("Street Name");

        cBoxAddressStreetSuffix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFieldAddressAux.setText("Aux");

        txtFieldAddressCity.setText("City");

        lUserAddressState.setText("State");

        cBoxAddressState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFieldAddressZipCode.setText("Zip Code");

        txtFieldPhoneNumber.setText("Phone Number");

        lCar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lCar.setText("Car");

        lCarType.setText("Type");

        bGroupCarType.add(rButtonCarTypeCompact);
        rButtonCarTypeCompact.setText("Compact");

        bGroupCarType.add(rButtonCarTypeMidSized);
        rButtonCarTypeMidSized.setText("Mid Sized");

        bGroupCarType.add(rButtonCarTypeSUV);
        rButtonCarTypeSUV.setText("SUV");

        lAddPackage.setText("Add Package");

        cBoxCarPackage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bAddCarPackage.setText("Add");

        lCarPackages.setText("Car Packages");

        bRemoveCarPackage.setText("Remove");

        lDelivery.setText("Delivery");

        cBoxDelivery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lCarPrice.setText("Car Price: ");

        lPackagePrice.setText("Price of Packages: ");

        lDeliveryPrice.setText("Price of Delivery: ");

        bSubmit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bSubmit.setText("Submit Order");

        listCarPackages.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCarPackages);

        lUserPhoneNumber.setText("Phone Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lAddPackage)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBoxCarPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bAddCarPackage))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lCar)
                                .addComponent(lCarType)
                                .addComponent(rButtonCarTypeMidSized)
                                .addComponent(rButtonCarTypeCompact)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(rButtonCarTypeSUV)
                                    .addGap(36, 36, 36))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDelivery)
                            .addComponent(cBoxDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lCarPackages)
                                    .addComponent(bRemoveCarPackage))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lUserAddress)
                                    .addComponent(lUserName)
                                    .addComponent(lUser)
                                    .addComponent(txtFieldAddressAux, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFieldAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cBoxAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lUserAddressState))
                                    .addComponent(txtFieldAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lUserPhoneNumber)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(txtFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bSubmit))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(txtFieldAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cBoxAddressStreetDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFieldAddressStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cBoxAddressStreetSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCarPrice)
                                .addGap(18, 18, 18)
                                .addComponent(lCarPriceNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lPackagePrice)
                                .addGap(18, 18, 18)
                                .addComponent(lPackagePriceNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lDeliveryPrice)
                                .addGap(18, 18, 18)
                                .addComponent(lDeliveryPriceNumber)))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelCarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCarPrice)
                            .addComponent(lCarPriceNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPackagePrice)
                            .addComponent(lPackagePriceNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDeliveryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDeliveryPriceNumber))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lUser)
                        .addGap(18, 18, 18)
                        .addComponent(lUserName)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lUserAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBoxAddressStreetDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldAddressStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBoxAddressStreetSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldAddressAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBoxAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lUserAddressState))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lUserPhoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lCar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCarType)
                            .addComponent(lDelivery))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rButtonCarTypeCompact)
                            .addComponent(cBoxDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rButtonCarTypeMidSized)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rButtonCarTypeSUV)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAddPackage)
                            .addComponent(lCarPackages))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bRemoveCarPackage)
                                    .addComponent(bSubmit)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cBoxCarPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bAddCarPackage)))
                        .addGap(66, 66, 66))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_GUICustomCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_GUICustomCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_GUICustomCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_GUICustomCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_GUICustomCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddCarPackage;
    private javax.swing.ButtonGroup bGroupCarType;
    private javax.swing.JButton bRemoveCarPackage;
    private javax.swing.JButton bSubmit;
    private javax.swing.JComboBox<String> cBoxAddressState;
    private javax.swing.JComboBox<String> cBoxAddressStreetDirection;
    private javax.swing.JComboBox<String> cBoxAddressStreetSuffix;
    private javax.swing.JComboBox<String> cBoxCarPackage;
    private javax.swing.JComboBox<String> cBoxDelivery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAddPackage;
    private javax.swing.JLabel lCar;
    private javax.swing.JLabel lCarPackages;
    private javax.swing.JLabel lCarPrice;
    private javax.swing.JLabel lCarPriceNumber;
    private javax.swing.JLabel lCarType;
    private javax.swing.JLabel lDelivery;
    private javax.swing.JLabel lDeliveryPrice;
    private javax.swing.JLabel lDeliveryPriceNumber;
    private javax.swing.JLabel lPackagePrice;
    private javax.swing.JLabel lPackagePriceNumber;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lUserAddress;
    private javax.swing.JLabel lUserAddressState;
    private javax.swing.JLabel lUserName;
    private javax.swing.JLabel lUserPhoneNumber;
    private javax.swing.JLabel labelCarImage;
    private javax.swing.JList<String> listCarPackages;
    private javax.swing.JRadioButton rButtonCarTypeCompact;
    private javax.swing.JRadioButton rButtonCarTypeMidSized;
    private javax.swing.JRadioButton rButtonCarTypeSUV;
    private javax.swing.JTextField txtFieldAddressAux;
    private javax.swing.JTextField txtFieldAddressCity;
    private javax.swing.JTextField txtFieldAddressNumber;
    private javax.swing.JTextField txtFieldAddressStreetName;
    private javax.swing.JTextField txtFieldAddressZipCode;
    private javax.swing.JTextField txtFieldFirstName;
    private javax.swing.JTextField txtFieldLastName;
    private javax.swing.JTextField txtFieldPhoneNumber;
    // End of variables declaration//GEN-END:variables

    // Getters
    public String getFirstName() { return txtFieldFirstName.getText(); }
    public String getLastName() { return txtFieldLastName.getText(); }
    public int getAddressState() { return cBoxAddressState.getSelectedIndex(); }
    public int getAddressStreetDirection() { return cBoxAddressStreetDirection.getSelectedIndex(); }
    public int getAddressStreetPrefix() { return cBoxAddressStreetSuffix.getSelectedIndex(); }
    public int getCarPackage() { return cBoxCarPackage.getSelectedIndex(); }
    public ArrayList<String> getSelectedCarPackages() { 
        ArrayList<String> empty = new ArrayList<String>();
        if (listCarPackages.getSelectedValuesList().size() > 0)
            return (ArrayList)listCarPackages.getSelectedValuesList();
        else
            return empty;
    }
    public int getDelivery() { return cBoxDelivery.getSelectedIndex(); }
    public int getSelectedCarType() {
        int i = 0;
        if (rButtonCarTypeCompact.isSelected())
            i = 1;
        if (rButtonCarTypeMidSized.isSelected())
            i = 2;
        if (rButtonCarTypeSUV.isSelected())
            i = 3;
        return i;
    }

    // Setters
    public void setCBoxAddressState(String[] s) {
        cBoxAddressState.setModel(new DefaultComboBoxModel(s));
    }
    public void setCBoxAddressStreetDirection(String[] s) {
        cBoxAddressStreetDirection.setModel(new DefaultComboBoxModel(s));
    }
    public void setCBoxAddressStreetSuffix(String[] s) {
        cBoxAddressStreetSuffix.setModel(new DefaultComboBoxModel(s));
    }
    public void setCBoxCarPackage(String[] s) {
        cBoxCarPackage.setModel(new DefaultComboBoxModel(s));
    }
    public void setPackages(String[] s) {
        listCarPackages.setListData(s);
    }
    public void setCarPrice(String s) {
        lCarPriceNumber.setText(s);
    }
    public void setPackagePrice(String s) {
        lPackagePriceNumber.setText(s);
    }
    public void setDeliveryPrice(String s) {
        lDeliveryPriceNumber.setText(s);
    }
    
    // Saving old method for reference.
    //public void setCarImageCompact() {
        //try {
        //BufferedImage myPicture = ImageIO.read(new File("images/Compact.png"));
        //labelTestImage.setIcon(new ImageIcon(myPicture));
        //}
        //catch (IOException ex) { }
    //}
    public void setCarImageCompact() {
        java.net.URL carIcon = View_GUICustomCars.class.getResource("/images/Compact.png");
        if (carIcon != null)
        labelCarImage.setIcon(new ImageIcon(carIcon));
    }
    public void setCarImageMidSized() {
        java.net.URL carIcon = View_GUICustomCars.class.getResource("/images/MidSized.png");
        if (carIcon != null)
        labelCarImage.setIcon(new ImageIcon(carIcon));
    }
    public void setCarImageSUV() {
        java.net.URL carIcon = View_GUICustomCars.class.getResource("/images/SUV.png");
        if (carIcon != null)
        labelCarImage.setIcon(new ImageIcon(carIcon));
    }

    
    // Listeners
    
    // Add Car Package Button
    void addBAddCarPackageListener(ActionListener listenForBAddCarPackage) {
        bAddCarPackage.addActionListener(listenForBAddCarPackage);
    }
    // Remove Car Package Button
    void addBRemoveCarPackageListener(ActionListener listenForBRemoveCarPackage) {
        bRemoveCarPackage.addActionListener(listenForBRemoveCarPackage);
    }
    // Submit Order Button
    void addBSubmitListener(ActionListener listenForBSubmit) {
        bSubmit.addActionListener(listenForBSubmit);
    }


    // Car Type Radio Buttons
    void addRButtonCarTypeCompactListener(ActionListener listenForRButtonCarTypeCompact) {
        rButtonCarTypeCompact.addActionListener(listenForRButtonCarTypeCompact);
    }
    void addRButtonCarTypeMidSizedListener(ActionListener listenForRButtonCarTypeMidSized) {
        rButtonCarTypeMidSized.addActionListener(listenForRButtonCarTypeMidSized);
    }
    void addRButtonCarTypeSUVListener(ActionListener listenForRButtonCarTypeSUV) {
        rButtonCarTypeSUV.addActionListener(listenForRButtonCarTypeSUV);
    }
    
    // Delivery Combo Box
    void addCBoxDeliveryListener(ActionListener listenForCBoxDelivery) {
        cBoxDelivery.addActionListener(listenForCBoxDelivery);
    }
    
    // Display Message
    void displayMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
}
